log("data-final-fixes-start")
local Deadlock = require("utils/deadlock")
Deadlock.MakeStackedRecipes()
Deadlock.DensityOverride()
Deadlock.FixLocalisedNames()
Deadlock.SubGroups()
log("data-final-fixes-end")
